version: "3.9"

services:
  nginx:
    build:
      context: docker/desenvolvimento
      dockerfile: nginx/Dockerfile
    environment:
      SERVER_NAME: ${DOMAIN_NAME}
    ports:
      - "8880:80"
      - "4443:443"
    volumes:
      - ./app:/app
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/desenvolvimento
      dockerfile: php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=${DOMAIN_NAME}
    volumes:
      - ./app:/app

  # php-cli:
  #   build:
  #     context: docker/desenvolvimento
  #     dockerfile: php-cli/Dockerfile
  #   volumes:
  #     - ./app:/app

  mysql:
    image: mysql:8
    container_name: mysql_banco_de_dados
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./app/db-init:/docker-entrypoint-initdb.d    
      - mysql_data:/var/lib/mysql:rw      

volumes:
  mysql_data:   